# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Gradle Test

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]


permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Use Gradle 8.7
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          mkdir -p /opt/gradle
          unzip -d /opt/gradle gradle-8.7-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-8.7/bin
          gradle --version
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test With Gradle
        run: ./gradlew --info test
